name: nncomp
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - librosa
  - scipy
  - numpy
  - pip
  - pip:
    - tensorboard
    - auraloss

